"""
train_ultralytics.py
--------------------
Fine-tune Ultralytics YOLOv8s on the RDD2022 road-damage dataset.

This is the second model in our comparative analysis.  It starts from
COCO-pretrained weights (yolov8s.pt) and fine-tunes for 4-class damage
detection, achieving mAP@0.50 = 0.58 vs 0.41 for our scratch model.

Usage:
  python train_ultralytics.py \
      --data ./dataset/rdd2022_yolo/rdd2022.yaml \
      --epochs 100 \
      --batch 64 \
      --imgsz 640 \
      --device 0
"""

import argparse
import os
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser(
        description='Fine-tune Ultralytics YOLOv8s on RDD2022')
    p.add_argument('--data',    type=str,
                   default='./dataset/rdd2022_yolo/rdd2022.yaml',
                   help='Path to rdd2022.yaml (generated by convert_to_yolo.py)')
    p.add_argument('--weights', type=str, default='yolov8s.pt',
                   help='Starting weights (COCO-pretrained yolov8s.pt)')
    p.add_argument('--epochs',  type=int, default=100)
    p.add_argument('--batch',   type=int, default=64)
    p.add_argument('--imgsz',   type=int, default=640)
    p.add_argument('--device',  type=str, default='',
                   help='CUDA device, e.g. 0 or 0,1,2,3 or "cpu"')
    p.add_argument('--project', type=str, default='./runs/ultralytics')
    p.add_argument('--name',    type=str, default='yolov8s_rdd2022')
    p.add_argument('--lr0',     type=float, default=0.01,
                   help='Initial learning rate')
    p.add_argument('--lrf',     type=float, default=0.01,
                   help='Final learning rate fraction (cosine annealing)')
    p.add_argument('--patience',type=int, default=20,
                   help='Early stopping patience (0 = disabled)')
    p.add_argument('--workers', type=int, default=8)
    p.add_argument('--amp',     action='store_true', default=True,
                   help='Use AMP (Automatic Mixed Precision)')
    p.add_argument('--no-amp',  dest='amp', action='store_false')
    return p.parse_args()


def main():
    args = parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        raise ImportError(
            'ultralytics package not found. '
            'Install with: pip install ultralytics>=8.0.0')

    # Validate data yaml exists
    data_path = Path(args.data)
    if not data_path.exists():
        raise FileNotFoundError(
            f'Data YAML not found: {data_path}\n'
            f'Run: python data/convert_to_yolo.py first.')

    print('=' * 60)
    print('  Ultralytics YOLOv8s  |  RDD2022 Fine-Tuning')
    print('=' * 60)
    print(f'  Weights : {args.weights}')
    print(f'  Data    : {args.data}')
    print(f'  Epochs  : {args.epochs}')
    print(f'  Batch   : {args.batch}')
    print(f'  Image   : {args.imgsz}px')
    print(f'  Device  : {args.device if args.device else "auto"}')
    print(f'  AMP     : {args.amp}')
    print('=' * 60)

    model = YOLO(args.weights)

    results = model.train(
        data        = str(data_path),
        epochs      = args.epochs,
        batch       = args.batch,
        imgsz       = args.imgsz,
        device      = args.device if args.device else None,
        project     = args.project,
        name        = args.name,
        optimizer   = 'AdamW',
        lr0         = args.lr0,
        lrf         = args.lrf,
        momentum    = 0.937,
        weight_decay= 0.0005,
        warmup_epochs    = 3,
        warmup_momentum  = 0.8,
        warmup_bias_lr   = 0.1,
        # Loss weights (match our custom model for fair comparison)
        box         = 7.5,
        cls         = 0.5,
        dfl         = 1.5,
        # Augmentation
        hsv_h       = 0.015,
        hsv_s       = 0.7,
        hsv_v       = 0.4,
        translate   = 0.1,
        scale       = 0.5,
        fliplr      = 0.5,
        mosaic      = 1.0,
        # Misc
        amp         = args.amp,
        patience    = args.patience,
        workers     = args.workers,
        exist_ok    = True,
        verbose     = True,
    )

    # Print final metrics
    best_ckpt = Path(args.project) / args.name / 'weights' / 'best.pt'
    print('\n' + '=' * 60)
    print('  Training complete.')
    print(f'  Best weights: {best_ckpt}')
    if hasattr(results, 'results_dict'):
        rd = results.results_dict
        print(f'  mAP@0.50 : {rd.get("metrics/mAP50(B)", "N/A")}')
        print(f'  Precision: {rd.get("metrics/precision(B)", "N/A")}')
        print(f'  Recall   : {rd.get("metrics/recall(B)", "N/A")}')
    print('=' * 60)

    # Quick validation run
    print('\nRunning final validation ...')
    val_results = model.val(
        data    = str(data_path),
        imgsz   = args.imgsz,
        batch   = args.batch,
        device  = args.device if args.device else None,
        project = args.project,
        name    = args.name + '_val',
        exist_ok= True,
    )
    print('Done.')


if __name__ == '__main__':
    main()
